### ISSUE TITLE
Emotes/emojis higher than words?

### ISSUE THREAD

**Issue by MaxHasBeenUsed** [gepz/userscript#2]
Examples:
+ Membership emotes:
![图片](https://user-images.githubusercontent.com/63943573/204543861-1020dbe7-632c-4ba6-bb94-75f71fe86b9f.png)
+ Emojis:
![图片](https://user-images.githubusercontent.com/63943573/204544384-8c7a6fa8-1b53-44e1-949a-2411a24460ad.png)

Font chosen in setting panel: Sans-serif
Platform: Windows (Microsoft Yahei has been modified)
Font used in YouTube UI elements: Source Han Sans

I don't know for sure but it seem to be a font-related thing? If more info is needed, I'd be happy to provide.

**Comment by gepz** [comment]
I'll look into it.

It would be great if you could share a link to a video that exhibits the issue.

**Comment by MaxHasBeenUsed** [comment]
It is confirmed that the cause is "Source Han Sans (思源黑体)" font I use. So the issue can be reproduced when you set the font to "SHS" in the script's settings panel.

The thing is, I'm using Stylus to force youtube.com to use that font for better readability, something like:
```
@moz-document regexp (".+youtube.com/watch\?\w+"){
:not([class*="icon"]):not([class*="button"]):not([class*=mjx]):not([class*=fa]):not(i):not([class*='glyph']):not([class*='vjs-']){
    font-family: "思源黑体" !important
}
}
```
The `!important` part is forcing `flow chat` to use "SHS" font, even though I don't mean it to.

So is there a workaround to the problem? Many thanks!

**Comment by gepz** [comment]
I would suggest adding
`:not([class*="fyc_chat"] *)`
 at the beginning of the third line.

**Comment by MaxHasBeenUsed** [comment]
It worked!　ありがとうございます！
