### ISSUE TITLE
Improving emoji resolution

### ISSUE THREAD

**Issue by lovesyk** [gepz/userscript#3]
Thank you for the great work maintaining Flow Youtube Chat!

I noticed that emoji are often of low quality because of the resolution Google resizes them to when being posted into the chat.
Example of the resized URL: `https://yt3.ggpht.com/Ov1AltJutvSzsJm0wI4zZM5pJdRkR22Xd4kfNDKNK0mBAaBKMw6ON4u8vWKpGaVGtucVUGJ11A=w24-h24-c-k-nd`
Original resolution:
`https://yt3.ggpht.com/Ov1AltJutvSzsJm0wI4zZM5pJdRkR22Xd4kfNDKNK0mBAaBKMw6ON4u8vWKpGaVGtucVUGJ11A`

Current script result:
![before](https://user-images.githubusercontent.com/9806747/209465005-d4a2a61e-6783-4fcf-85ce-7dcea08916ca.jpg)
Result after stripping away `=w**-h**-c-k-nd` from the URL:
![after](https://user-images.githubusercontent.com/9806747/209465023-6d706a2f-2a01-47aa-a437-9888473b01a9.jpg)

It probably doesn't make much sense to try to calculate the required resolution since the video can be resized to any resolution at any time. Would it be possible to simply strip away the resolution parameter from all emoji?

**Comment by 1fRP111b1f6M1** [comment]
Thanks for the feedback.
The full-sized version of emoji images will now be used in flow chats to display them with higher quality in the latest version.

**Comment by lovesyk** [comment]
Working great, thank you!
